
  <m:item name='栏目管理' link='../exam/admin.php?ct=examtype' rank='' target='main' />
  <m:item name='问题管理' link='../exam/admin.php?ct=issue' rank='' target='main' />
  <m:item name='答案管理' link='../exam/admin.php?ct=answer' rank='' target='main' />
  <m:item name='卷宗管理' link='../exam/admin.php?ct=file' rank='' target='main' />
  <m:item name='相关设置' link='../exam/admin.php?ct=setting' rank='' target='main' />
