<?php
$z[0]=Array("spaceurl","",157,175);
$z[0][4]=array();
$z[1]=Array("face","",204,217);
$z[1][4]=array();
$z[2]=Array("spaceurl","",264,282);
$z[2][4]=array();
$z[3]=Array("uname","",301,315);
$z[3][4]=array();
$z[4]=Array("spaceurl","",365,383);
$z[4][4]=array();
$z[5]=Array("spaceurl","",461,479);
$z[5][4]=array();
$z[6]=Array("spaceurl","",550,568);
$z[6][4]=array();
$z[7]=Array("rankname","",697,715);
$z[7][4]=array();
$z[8]=Array("jointime","",783,835);
$z[8][4]=array();
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",903,956);
$z[9][4]=array();
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>