<?php
$z[0]=Array("array","\r\n          @me = (empty(@me['litpic']) ? \"<img src='[field:global.cfg_basehost/]/templets/mem/images/tuk1.jpg'>\" : \"<img src='{@me['litpic']}'/>\"); \r\n          ",16,217);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",277,292);
$z[1][4]=array();
$z[2]=Array("title","",294,345);
$z[2][4]=array();
$z[2][4]['function']="TitleReplace(\"MEM\",\"@me\")";
$z[3]=Array("infos","",369,383);
$z[3][4]=array();

?>